blinklabs-io/gouroboros

- protocol/blockfetch/blockfetch.go
- protocol/chainsync/chainsync.go
- protocol/handshake/handshake.go
- protocol/protocol.go
* add locking around protocol state
> Refactor mini-protocols (part 2)

- README.md
- block/allegra.go
- block/alonzo.go
- block/byron.go
- block/mary.go
- block/shelley.go
- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/localtxsubmission.go
- cmd/go-ouroboros-network/main.go
- ouroboros.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/localtxsubmission/messages.go
* split test program into subcommands
* update manual testing instructions
Fixes #9
> Implement local-tx-submission mini-protocol

- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/localtxsubmission.go
- cmd/go-ouroboros-network/main.go
- cmd/go-ouroboros-network/server.go
- ouroboros.go
- protocol/blockfetch/blockfetch.go
- protocol/chainsync/chainsync.go
- protocol/chainsync/messages.go
- protocol/handshake/handshake.go
- protocol/handshake/messages.go
- protocol/keepalive/keepalive.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/protocol.go
* basic server test program
* implement basic support for handshake version negotation
* move common mini-protocol options to separate struct
* track mode (NtN/NtC) and role (server/client) for protocol
Fixes #30
> Basic server support

- muxer/muxer.go
- ouroboros.go
> Fix race condition around handshake and muxer protocol registration

- cmd/go-ouroboros-network/server.go
- protocol/handshake/handshake.go
> Signal that the handshake is complete when acting as server

- protocol/protocol.go
> Reuse raw CBOR from message if present

- muxer/segment.go
- protocol/protocol.go
> Split large messages across multiple segments when sending

- ouroboros.go
- protocol/protocol.go
- protocol/state.go
- protocol/txsubmission/messages.go
- protocol/txsubmission/txsubmission.go
> Implement TxSubmission protocol (part 1)

- protocol/blockfetch/blockfetch.go
- protocol/chainsync/chainsync.go
- protocol/handshake/handshake.go
- protocol/keepalive/keepalive.go
- protocol/localstatequery/localstatequery.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/txsubmission/txsubmission.go
> Embed Protocol object in mini-protocol objects

- ouroboros.go
- protocol/localstatequery/localstatequery.go
- protocol/protocol.go
- versions.go
> Pass negotiated protocol version to mini-protocols

- protocol/blockfetch/messages.go
- protocol/chainsync/messages.go
- protocol/handshake/messages.go
- protocol/keepalive/messages.go
- protocol/localtxsubmission/messages.go
- protocol/txsubmission/messages.go
> Create New() functions for all message types

- cmd/go-ouroboros-network/chainsync.go
- protocol/blockfetch/blockfetch.go
- protocol/chainsync/chainsync.go
- protocol/handshake/handshake.go
- protocol/keepalive/keepalive.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/protocol.go
> Support for pipelining on send

- .github/workflows/golangci-lint.yml
- .github/workflows/pr.yml
- Makefile
- protocol/blockfetch/messages_test.go
- protocol/chainsync/messages_test.go
- protocol/handshake/messages_test.go
- protocol/keepalive/messages_test.go
- protocol/localstatequery/messages_test.go
- protocol/localtxsubmission/messages_test.go
- protocol/txsubmission/messages_test.go
> Unit test framework for protocol message CBOR encoding/decoding

- muxer/muxer.go
- ouroboros.go
- protocol/protocol.go
> feat: method to shutdown connection

- ouroboros.go
- ouroboros_test.go
> fix: don't panic when calling Close() after Dial() failure

- protocol/protocol.go
> fix: exit send/recv loops in Protocol on error

- muxer/muxer.go
> fix: use mutex to prevent race condition when stopping muxer

- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/localtxsubmission.go
- ouroboros.go
- protocol/blockfetch/blockfetch.go
- protocol/chainsync/chainsync.go
- protocol/handshake/handshake.go
- protocol/keepalive/keepalive.go
- protocol/localstatequery/localstatequery.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/protocol.go
- protocol/txsubmission/txsubmission.go
This decentralizes the protocol configuration and reduces resource usage
when not using all protocols.
Fixes #87
BREAKING CHANGE: protocols must now be explicitly started before they can be used
> feat!: require explicitly starting each protocol

- block/babbage.go
- block/common.go
- cmd/go-ouroboros-network/chainsync.go
- protocol/chainsync/chainsync.go
- versions.go
> feat: babbage era support

- cmd/go-ouroboros-network/localtxsubmission.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/localtxsubmission/messages.go
> feat: defer parsing localtxsubmission reject reason

- versions.go
> chore: update protocol versions

- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/main.go
- muxer/muxer.go
- ouroboros.go
- protocol/handshake/handshake.go
> feat: make diffusion mode configurable

- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/localtxsubmission.go
- options.go
- ouroboros.go
- protocol/blockfetch/blockfetch.go
- protocol/chainsync/chainsync.go
- protocol/handshake/handshake.go
- protocol/keepalive/keepalive.go
- protocol/localstatequery/localstatequery.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/txsubmission/txsubmission.go
> feat: functional options for protocol configs

- ouroboros.go
- protocol/handshake/client.go
- protocol/handshake/handshake.go
- protocol/handshake/server.go
- protocol/protocol.go
> feat: split handshake protocol into client/server

- ouroboros.go
- protocol/handshake/handshake.go
- protocol/keepalive/client.go
- protocol/keepalive/keepalive.go
- protocol/keepalive/server.go
> feat: split keepalive protocol into client and server

- cmd/go-ouroboros-network/chainsync.go
- protocol/blockfetch/blockfetch.go
- protocol/blockfetch/client.go
- protocol/blockfetch/server.go
> feat: split blockfetch protocol into client and server

- protocol/localstatequery/client.go
- protocol/localstatequery/localstatequery.go
- protocol/localstatequery/server.go
> feat: split localstatequery protocol into client and server

- cmd/go-ouroboros-network/chainsync.go
- protocol/chainsync/chainsync.go
- protocol/chainsync/client.go
- protocol/chainsync/server.go
> feat: split chainsync protocol into client and server

- cmd/go-ouroboros-network/localtxsubmission.go
- protocol/localtxsubmission/client.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/localtxsubmission/server.go
> feat: split localtxsubmission protocol into client and server

- protocol/txsubmission/client.go
- protocol/txsubmission/messages.go
- protocol/txsubmission/messages_test.go
- protocol/txsubmission/server.go
- protocol/txsubmission/txsubmission.go
> feat: split txsubmission protocol into client and server

- protocol/protocol.go
> feat: include message/state name in protocol error message

- protocol/handshake/client.go
> fix: only extract handshake version data for NtN

- cmd/go-ouroboros-network/localtxsubmission.go
- docker-compose.yml
- protocol/localtxsubmission/client.go
- protocol/localtxsubmission/error.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/localtxsubmission/server.go
> feat: make the localtxsubmission interface friendlier

- cmd/go-ouroboros-network/chainsync.go
- protocol/chainsync/chainsync.go
- protocol/chainsync/client.go
- protocol/chainsync/error.go
- protocol/chainsync/messages.go
- protocol/chainsync/server.go
> feat: make the chainsync interface friendlier

- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/main.go
- cmd/go-ouroboros-network/query.go
- protocol/chainsync/chainsync.go
- protocol/chainsync/client.go
- protocol/chainsync/messages.go
- protocol/chainsync/messages_test.go
- protocol/common/types.go
- protocol/localstatequery/client.go
- protocol/localstatequery/error.go
- protocol/localstatequery/localstatequery.go
- protocol/localstatequery/messages.go
- protocol/localstatequery/queries.go
This commit also moves the Point definition to a common package to make it easier to reuse. NOTE: many of the query result structures are not currently defined, but we can do those later
Fixes #44 and #109
> feat: finish implementing local-state-query

- cmd/go-ouroboros-network/query.go
- protocol/localstatequery/client.go
- protocol/localstatequery/queries.go
This was supposed to cover a lot more, but many of the result types are either poorly documented or we cannot currently parse due to maps with bytestring keys
Fixes #134
> feat: flesh out query result types

- ouroboros.go
> feat: better handling of EOF errors

- cmd/go-ouroboros-network/chainsync.go
- protocol/chainsync/client.go
> feat: support for getting chain tip via chain-sync

- go.mod
- go.sum
- protocol/localtxsubmission/client.go
- protocol/localtxsubmission/error.go
- protocol/localtxsubmission/messages.go
> feat: support for parsing TX reject reason CBOR

- cmd/go-ouroboros-network/localtxsubmission.go
- ouroboros.go
> feat: properly handle muxer error during handshake

- protocol/handshake/messages_test.go
> test: encode/decode unit tests for handshake messages

- protocol/localstatequery/messages_test.go
> test: encode/decode unit tests for localstatequery messages

- protocol/common/types.go
> docs: inline docs for protocol/common package

- protocol/handshake/handshake.go
- protocol/protocol.go
- protocol/state.go
> feat: support for timeouts on protocol state transitions

- README.md
- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/localtxsubmission.go
- cmd/go-ouroboros-network/query.go
- ouroboros.go
- protocol/blockfetch/blockfetch.go
- protocol/chainsync/chainsync.go
- protocol/handshake/handshake.go
- protocol/keepalive/keepalive.go
- protocol/localstatequery/localstatequery.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/txsubmission/txsubmission.go
> feat: functional options for mini-protocols

- protocol/keepalive/client.go
- protocol/keepalive/keepalive.go
> feat: make keep-alive timeout/period configurable

- protocol/handshake/client.go
- protocol/handshake/handshake.go
> feat: make handshake timeout configurable

- protocol/blockfetch/blockfetch.go
- protocol/blockfetch/client.go
> feat: make blockfetch timeout configurable

- protocol/txsubmission/client.go
- protocol/txsubmission/txsubmission.go
> feat: make txsubmission timeout configurable

- protocol/localstatequery/client.go
- protocol/localstatequery/localstatequery.go
> feat: make localstatequery timeouts configurable

- muxer/muxer.go
- muxer/segment.go
- ouroboros.go
- protocol/protocol.go
This also rearranges/renames a few things to make the code docs look better
Fixes #153
> docs: code docs for muxer package

- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/localtxsubmission.go
- cmd/go-ouroboros-network/mem_usage.go
- cmd/go-ouroboros-network/query.go
- options.go
- ouroboros.go
- versions.go
This also renames some internal types, vars, and consts to not show up in the docs
Fixes #152
> docs: code docs for ouroboros package

- protocol/blockfetch/blockfetch.go
- protocol/chainsync/chainsync.go
- protocol/handshake/handshake.go
- protocol/keepalive/keepalive.go
- protocol/localstatequery/localstatequery.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/message.go
- protocol/protocol.go
- protocol/state.go
- protocol/txsubmission/txsubmission.go
This also includes some rearranging/renaming of things to make the docs look better
Fixes #154
> docs: code docs for protocol package

- protocol/chainsync/chainsync.go
- protocol/chainsync/client.go
- protocol/chainsync/error.go
- protocol/chainsync/messages.go
- protocol/chainsync/messages_test.go
- protocol/chainsync/server.go
- protocol/chainsync/wrappers.go
This also renames some things to make the docs look better
Fixes #156
> docs: code docs for protocol/chainsync package

- utils/cbor.go
- utils/debug.go
- utils/utils.go
> docs: code docs for utils package

- protocol/localtxsubmission/client.go
- protocol/localtxsubmission/error.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/localtxsubmission/messages.go
- protocol/localtxsubmission/messages_test.go
- protocol/localtxsubmission/server.go
This also rearranges/renames some things to make the docs look better
Fixes #161
> docs: code docs for protocol/localtxsubmission

- protocol/localstatequery/client.go
- protocol/localstatequery/error.go
- protocol/localstatequery/localstatequery.go
- protocol/localstatequery/messages.go
- protocol/localstatequery/messages_test.go
- protocol/localstatequery/queries.go
- protocol/localstatequery/server.go
This also rearranges/renames a few things to make the docs look better
Fixes #160
> docs: code docs for protocol/localstatequery package

- .gitignore
- Makefile
- cmd/common/cmdline.go
- cmd/common/connect.go
- cmd/tx-monitor/main.go
- go.mod
- ouroboros.go
- protocol/localtxmonitor/client.go
- protocol/localtxmonitor/localtxmonitor.go
- protocol/localtxmonitor/messages.go
- protocol/localtxmonitor/messages_test.go
- protocol/localtxmonitor/server.go
- protocol/localtxsubmission/client.go
> feat: local-tx-monitor protocol

- README.md
- cmd/common/cmdline.go
- cmd/go-ouroboros-network/chainsync.go
- cmd/go-ouroboros-network/main.go
- networks.go
- options.go
> feat: allow specifying pre-defined networks

- cmd/go-ouroboros-network/chainsync.go
- go.mod
- go.sum
This also updates the test program to take advantage of the new ledger version
> chore: update cloudstruct/go-cardano-ledger to v0.5.0

- cmd/go-ouroboros-network/chainsync.go
- protocol/blockfetch/blockfetch.go
- protocol/blockfetch/client.go
- protocol/error.go
- protocol/localtxmonitor/client.go
> feat: simpler interface for blockfetch protocol

- .gitignore
- cmd/block-fetch/main.go
> feat: test program to fetch single block

- ledger/babbage.go
> fix: minor Babbage TX parsing fix

- ledger/alonzo.go
> fix: don't try to parse Alonzo witness set redeemers data

- protocol/chainsync/client.go
> fix: break out of sync loop on shutdown

- protocol/protocol.go
> fix: stop protocol state transition timer on shutdown

- cbor/cbor.go
- cbor/value.go
> feat: support for parsing trouble types in CBOR tags

- networks.go
> feat: add public root address/port for well-known networks

- protocol/chainsync/chainsync.go
- protocol/chainsync/client.go
> feat: make chainsync pipelining limit configurable

- protocol/chainsync/client.go
- protocol/chainsync/error.go
> feat: method to stop chainsync process

- cmd/gouroboros/chainsync.go
- ledger/byron.go
> feat: calculate Byron block absolute slot

- muxer/muxer.go
- ouroboros.go
- protocol/protocol.go
This is based on a fix originally submitted by safanaj in https://github.com/blinklabs-io/gouroboros/pull/250
Fixes https://github.com/blinklabs-io/gouroboros/issues/224 and https://github.com/blinklabs-io/gouroboros/issues/249
Co-authored-by: Marco Bardelli <bardelli.marco@gmail.com>
> fix: use sync.WaitGroup to avoid random panics on shutdown

- protocol/chainsync/client.go
> fix: return immediately when stopping sync process to prevent hang

- protocol/chainsync/chainsync.go
- protocol/chainsync/client.go
- protocol/chainsync/messages.go
- protocol/chainsync/server.go
- protocol/handshake/client.go
- protocol/handshake/handshake.go
- protocol/handshake/messages.go
- protocol/handshake/server.go
- protocol/localstatequery/client.go
- protocol/localstatequery/localstatequery.go
- protocol/localstatequery/messages.go
- protocol/localstatequery/server.go
- protocol/localtxmonitor/client.go
- protocol/localtxmonitor/localtxmonitor.go
- protocol/localtxmonitor/messages.go
- protocol/localtxmonitor/server.go
- protocol/localtxsubmission/client.go
- protocol/localtxsubmission/localtxsubmission.go
- protocol/localtxsubmission/messages.go
- protocol/localtxsubmission/server.go
> feat: make protocol identifiers public

- muxer/muxer.go
- ouroboros.go
- protocol/blockfetch/client.go
- protocol/chainsync/client.go
- protocol/handshake/client.go
- protocol/keepalive/client.go
- protocol/localtxmonitor/client.go
- protocol/localtxsubmission/client.go
- protocol/protocol.go
> fix: protect stop/start/close functions from being called again

- cmd/gouroboros/chainsync.go
- connection.go
- connection_options.go
- connection_test.go
> feat: rename Ouroboros to Connection

- cbor/decode.go
> fix: increase max nested levels for CBOR decoding

- cmd/block-fetch/main.go
- cmd/gouroboros/chainsync.go
- cmd/gouroboros/localtxsubmission.go
- cmd/gouroboros/mem_usage.go
- cmd/gouroboros/query.go
- cmd/peer-sharing/main.go
- cmd/tx-monitor/main.go
- connection.go
- connection_options.go
> feat: auto-start protocols with option to disable

- cbor/bytestring.go
- cbor/encode.go
- cbor/value.go
- internal/test/helpers.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/mary.go
- ledger/mary_test.go
Fixes #209
fix: proper CBOR encoding for ByteString
feat: generic CBOR encode function
test: helper function for decoding hex string without capturing error
> feat: proper parsing for multiasset TX outputs

- connection_test.go
- internal/test/ouroboros_mock/connection.go
- internal/test/ouroboros_mock/mock_test.go
- muxer/muxer.go
- protocol/handshake/client_test.go
- protocol/protocol.go
> feat: allow running multiple instances of a protocol in muxer

- cmd/block-fetch/main.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
Fixes #286
feat: option to display all block info in block-fetch example program
> feat: generic interface for TX inputs/outputs

- cmd/block-fetch/main.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/common.go
- ledger/mary.go
- ledger/mary_test.go
- ledger/shelley.go
- ledger/tx.go
> feat: better handling of Mary MultiAsset value

- ledger/block.go
- ledger/common.go
- ledger/common_test.go
> feat: asset fingerprint

- ledger/alonzo.go
- ledger/babbage.go
- ledger/common.go
- ledger/common_test.go
- ledger/mary.go
- ledger/mary_test.go
- ledger/shelley.go
- ledger/tx.go
> feat: JSON marshaling for TX inputs/outputs

- ledger/common.go
- ledger/common_test.go
Fixes #302
feat: add function to create Address from bech32 string
> feat: return stake address from address

- cbor/value.go
- cbor/value_test.go
> feat: support for CBOR tags for arbitrarily large ints

- ledger/common.go
- ledger/common_test.go
> feat: build Address from parts

- cbor/cbor.go
- cbor/value.go
> feat: support for decoding rational numbers in CBOR

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
Implement transaction fee. Closes #329
> feat: transaction fee

- cmd/block-fetch/main.go
- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/block.go
- ledger/byron.go
- ledger/common.go
- ledger/mary.go
- ledger/shelley.go
> feat: better support for issuer vkey

- protocol/localtxsubmission/server.go
> feat: finish implementing server side of local-tx-submission

- protocol/localtxmonitor/localtxmonitor.go
- protocol/localtxmonitor/server.go
> feat: finish implementing server side of local-tx-monitor

- ledger/block.go
- ledger/conway.go
- ledger/era.go
- ledger/tx.go
- protocol/chainsync/client.go
> feat: conway era support

- connection.go
> feat: make connection shutdown async

- protocol/handshake/client.go
- protocol/handshake/versiondata.go
> feat: types for handshake version data

- internal/test/ouroboros_mock/connection.go
- protocol/handshake/client_test.go
- protocol/handshake/server.go
- protocol/handshake/server_test.go
> feat: handshake server-side refusal

- cbor/cbor.go
- cbor/value.go
- cbor/value_test.go
> feat: direct marshal/unmarshal for cbor.Constructor

- connection_manager.go
- connection_manager_test.go
- connection_test.go
- internal/test/ouroboros_mock/connection.go
- internal/test/ouroboros_mock/entry.go
- internal/test/ouroboros_mock/mock_test.go
- protocol/handshake/client_test.go
- protocol/handshake/server_test.go
- protocol/keepalive/client.go
- protocol/keepalive/keepalive.go
- topology.go
> feat: connection manager

- ledger/era.go
- protocol/chainsync/client.go
> feat: move block header to block type map to ledger

- protocol/blockfetch/blockfetch.go
- protocol/blockfetch/messages.go
- protocol/blockfetch/server.go
> feat: blockfetch server support

- connection.go
> feat: connect timeout on dial

- ledger/alonzo.go
- ledger/babbage.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
> feat: support for parsing transaction output from CBOR

- protocol/keepalive/client.go
> fix: don't send double keep-alives

- protocol/protocol.go
> fix: protocol shutdown deadlocks

- connection.go
> fix: shutdown connection on handshake protocol error

- connection.go
- muxer/muxer.go
- protocol/protocol.go
> fix: protect against send on closed channel panics

- muxer/muxer.go
> fix: adding locking around muxer protocol receivers map to prevent data race

- connection_manager.go
- connection_manager_test.go
> feat: connection manager notify on conn close with no error

- protocol/keepalive/client.go
> fix: add locking around keepalive timer

- internal/test/ouroboros_mock/connection.go
> fix: exit goroutine on close in ouroboros_mock

- connection.go
- connection_options.go
- protocol/peersharing/client.go
- protocol/peersharing/messages.go
- protocol/versiondata.go
- protocol/versions.go
> feat: update peer-sharing protocol

- protocol/peersharing/peersharing.go
- protocol/peersharing/server.go
> feat: peer-sharing server support

- protocol/peersharing/peersharing.go
- protocol/txsubmission/client.go
- protocol/txsubmission/messages.go
- protocol/txsubmission/server.go
- protocol/txsubmission/txsubmission.go
> docs: type/function docs for TxSubmission protocol

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
> feat: reference inputs in transaction interface

- protocol/keepalive/client.go
> feat: check keep-alive response cookie

- cmd/gouroboros/query.go
- ledger/common.go
- protocol/localstatequery/client.go
- protocol/localstatequery/queries.go
This adds support for the StakeDistribution, StakePools, and StakePoolParams queries.
Fixes #553
> feat: localstatequery stake-related queries

- protocol/localtxsubmission/client_test.go
> test: localtxsubmission client tests

- protocol/blockfetch/client_test.go
This tests a positive and negative response to fetching a particular block
Fixes #319
> test: blockfetch client tests

- Makefile
- connection.go
This adds a connection ID composed of the local and remote address of the connection.
Fixes #571
> feat: connection ID

- protocol/handshake/server.go
> feat: add a timeout for handshake propose on server side

- ledger/common.go
- ledger/common_test.go
> fix: better handling for addresses with trailing junk

- muxer/muxer.go
- protocol/blockfetch/server.go
- protocol/chainsync/server.go
- protocol/peersharing/server.go
- protocol/protocol.go
- protocol/txsubmission/server.go
This allows a connected peer to start a protocol, stop it, and later start it again within the same connection
Fixes #452
> feat: support for restarting server protocols

- ledger/verify_kes.go
Copy the KES verification functions from
https://github.com/cardano-foundation/cardano-ibc-incubator with minimal modifications.
> feat: kes verification functions

- go.mod
- go.sum
- ledger/verify_vrf.go
Copy the VRF verification functions from
https://github.com/cardano-foundation/cardano-ibc-incubator with minimal modifications.
> feat: vrf verification functions

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/certs.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
- ledger/verify_block_body.go
- protocol/localstatequery/queries.go
This adds support for decoding the various certificate types available in Shelley through Babbage for things like state pool registration and delegation
Fixes #331
> feat: ledger support for TX certificates

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/babbage_test.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This provides a method for returning the total collateral of a transaction
Fixes #341
> feat: TX total collateral support

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This adds support for decoding and retrieving staking withdrawals from a TX
Fixes #332
> feat: TX staking withdrawals support

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This adds support for decoding and retrieving Conway voting procedures from a TX
Fixes #343
> feat: TX voting procedures attribute support

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This adds a method to retrieve the required signers for a TX
Fixes #339
> feat: TX required signers attribute

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This adds a method for retrieving any asset mints from a TX
Fixes #336
> feat: TX asset mint attribute

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This adds a method for retrieving the script data hash from a TX
Fixes #337
> feat: TX script data hash attribute

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This adds a method for retrieving the validity interval start from a TX
Fixes #335
> feat: TX validity interval start attribute

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This adds a method for retrieving the auxiliary data hash from a TX
Fixes #334
> feat: TX auxiliary data hash attribute

- README.md
- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
This adds a method to retrieve the donation attribute from a TX
Fixes #627
> feat: TX donation attribute

- ledger/certs.go
> feat: support for Conway era certificates

- ledger/allegra.go
- ledger/alonzo.go
- ledger/babbage.go
- ledger/byron.go
- ledger/conway.go
- ledger/mary.go
- ledger/shelley.go
- ledger/tx.go
> feat: include UTxO ID with produced TX outputs

- go.mod
- go.sum
- ledger/alonzo.go
- ledger/babbage.go
- ledger/babbage_test.go
> chore(deps): bump utxorpc/go-codegen to 0.8.0

- ledger/shelley/genesis.go
- ledger/shelley/genesis_test.go
> feat: Shelley genesis config

- ledger/byron/genesis.go
- ledger/byron/genesis_test.go
> feat: Byron genesis config

- protocol/chainsync/server.go
- protocol/chainsync/server_test.go
> fix: remove unutilized 'msg' from handleRequestNext() 

- ledger/allegra/allegra.go
- ledger/allegra/pparams.go
- ledger/allegra/pparams_test.go
- ledger/common/pparams.go
- ledger/common/pparams_test.go
- ledger/shelley/pparams.go
- ledger/shelley/pparams_test.go
* update protocol parameter set from protocol param update spec
* move protocol params Nonce type to common
Fixes #742
> feat: Allegra protocol param updates

- ledger/allegra/pparams.go
- ledger/alonzo/pparams.go
- ledger/babbage/pparams.go
- ledger/common/pparams.go
- ledger/conway/pparams.go
- ledger/conway/pparams_test.go
> feat: add Utxorpc support for cardano.PParams in Conway

- ledger/allegra/pparams.go
- ledger/allegra/pparams_test.go
- ledger/alonzo/pparams.go
- ledger/alonzo/pparams_test.go
- ledger/babbage/pparams.go
- ledger/babbage/pparams_test.go
- ledger/mary/pparams.go
- ledger/mary/pparams_test.go
- ledger/shelley/pparams.go
- ledger/shelley/pparams_test.go
> feat: add Utxorpc support for cardano.PParams in other eras

- ledger/allegra/allegra.go
- ledger/alonzo/alonzo.go
- ledger/babbage/babbage.go
- ledger/block.go
- ledger/byron/byron.go
- ledger/conway/conway.go
- ledger/mary/mary.go
- ledger/shelley/shelley.go
> feat: expose previous block hash in block interface

- ledger/conway/rules.go
Consume the deposit for RegistrationCertificate and produce deposit value for DeregistrationCertificate
> fix(ledger): conway consume/produce deposits from (de)registration

- connection.go
> refactor: wait for connection close

- ledger/conway/conway.go
This retains data ordering when the original on-chain data was ordered
Fixes #1070
> fix: store redeemers in legacy format when needed

- ledger/conway/conway.go
> fix: Conway redeemer CBOR marshaling

- ledger/common/common.go
- ledger/common/common_test.go
> feat: helper functions to convert hashes to PlutusData
