ouroboros.go, utils/cbor.go, versions.go
* create version map for NtN and NtC
* switch CBOR encoding mode to ensure ordered map keys
=> Properly support protocol versions

protocol/blockfetch/blockfetch.go, protocol/blockfetch/messages.go, protocol/chainsync/chainsync.go, protocol/chainsync/messages.go, protocol/handshake/handshake.go, protocol/handshake/messages.go, protocol/keepalive/keepalive.go, protocol/keepalive/messages.go, protocol/localtxsubmission/localtxsubmission.go, protocol/localtxsubmission/messages.go
* export protocol message types and "new" functions
* export protocol state maps
* use a wrapper function to denote NtN vs. NtC in chain-sync when
parsing messages from CBOR
=> Minor refactor to make library more composable

protocol/blockfetch/blockfetch.go, protocol/chainsync/chainsync.go, protocol/handshake/handshake.go, protocol/keepalive/keepalive.go, protocol/localtxsubmission/localtxsubmission.go, protocol/protocol.go
=> Pass along whether message is a response to the handler

protocol/blockfetch/client.go, protocol/chainsync/client.go, protocol/handshake/client.go, protocol/keepalive/client.go, protocol/localtxsubmission/client.go, protocol/localtxsubmission/localtxsubmission.go, protocol/state.go
This also adds a helper function to make a copy of the protocol state map so that we're not modifying the default one
Fixes #170
=> feat: make localtxsubmission timeout configurable

cmd/go-ouroboros-network/chainsync.go, ledger/alonzo.go, ledger/babbage.go, ledger/mary.go
* don't try to parse arbitrary plutus scripts/data
* add missing transaction witness set field
* better support alternate transaction output format
* update Babbage intersect point for preview in test program
Fixes #204
=> fix: Babbage block parsing

cbor/cbor.go, cbor/decode.go, ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/mary.go, ledger/shelley.go, protocol/chainsync/messages.go
This also changes the following:
* rearrange generic CBOR parsing utility to be able to be used separately from storing the CBOR
* better ledger decode error messages
=> fix: store block type/CBOR in MsgRollForwardNtC

ledger/byron.go
=> fix: use correct prefix values for Byron block hash

ledger/shelley.go
=> fix: don't try to parse Shelley TX certificates for now

cmd/gouroboros/chainsync.go, protocol/chainsync/client.go
=> feat: function to get available block range for chain-sync

protocol/chainsync/client.go
=> fix: clear out intersect result channel when getting tip to prevent hangs

internal/test/ouroboros_mock/connection.go, muxer/muxer.go, ouroboros.go
This also stops the muxer on mock connection close
Fixes https://github.com/blinklabs-io/gouroboros/issues/257
=> fix: close connection on muxer stop

.gitignore, cmd/peer-sharing/main.go, connection.go, connection_options.go, protocol/handshake/client.go, protocol/handshake/handshake.go, protocol/peersharing/client.go, protocol/peersharing/messages.go, protocol/peersharing/messages_test.go, protocol/peersharing/peersharing.go, protocol/peersharing/server.go, versions.go
This implementation isn't entirely finished, but there's not yet a released version of cardano-node supporting this protocol to test against
Fixes #14
=> feat: peer sharing protocol

protocol/localstatequery/queries.go
Fixes https://github.com/blinklabs-io/gouroboros/issues/274
BREAKING CHANGES:
The protocol-params query will no longer work against cardano-node
<8.0.0 due to a backwards-incompatible change that upstream made
without proper protocol versioning
=> fix: adjust protocol-params query result for 8.0.0

connection.go
A server can apparently decide to respond with the full-duplex flag enabled in the NtN version data even when we had it disabled in the selected version in the handshake request
=> fix: only act in full-duplex mode if we asked for it

cbor/value.go, cmd/block-fetch/main.go, ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/block.go, ledger/byron.go, ledger/mary.go, ledger/shelley.go, ledger/tx.go
Fixes #294 and #295
feat: add Metadata() function to Transaction interface
=> feat: return full transaction instead of just the body

cbor/value.go
=> fix: recover panics when decoding CBOR maps

cbor/cbor.go, cbor/decode.go, cbor/value.go, cbor/value_test.go, cmd/block-fetch/main.go, internal/test/helpers.go, ledger/error.go
=> feat: generate JSON for arbitrary CBOR

.gitignore, cmd/tx-submission/main.go, protocol/txsubmission/client.go, protocol/txsubmission/messages.go, protocol/txsubmission/messages_test.go, protocol/txsubmission/server.go, protocol/txsubmission/txsubmission.go
=> feat: finish basic tx-submission client implementation

cmd/block-fetch/main.go, ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/mary.go, ledger/shelley.go, ledger/tx.go
=> feat: use pointer for TX metadata to better handle nil value

ledger/byron.go
=> fix: parse Byron transaction as array

protocol/txsubmission/server.go, protocol/txsubmission/txsubmission.go
=> feat: finish implementing server side of tx-submission

protocol/blockfetch/client.go, protocol/blockfetch/server.go, protocol/chainsync/client.go, protocol/chainsync/server.go, protocol/handshake/client.go, protocol/handshake/server.go, protocol/keepalive/client.go, protocol/keepalive/server.go, protocol/localstatequery/client.go, protocol/localstatequery/server.go, protocol/localtxmonitor/client.go, protocol/localtxmonitor/server.go, protocol/localtxsubmission/client.go, protocol/localtxsubmission/server.go, protocol/peersharing/client.go, protocol/peersharing/server.go, protocol/protocol.go, protocol/txsubmission/client.go, protocol/txsubmission/server.go
This information was useful in the past, but improvements in protocol handling and the muxer have made is unnecessary
=> chore: remove unused isResponse param in message handlers

ledger/common.go, networks.go
=> fix: use correct address network ID for testnets

connection_manager.go
This adds locking around access to the connection map to avoid a panic due concurrent read/write
Fixes #476
=> fix: add locking around connection manager connections

connection.go
We don't need to close handshakeFinishedChan, since the only place we wait on it also is watching for doneChan to be closed
=> fix: avoid race condition on shutdown during handshake

muxer/muxer.go, protocol/handshake/server_test.go
=> fix: remove use of sync.Once to avoid deadlocks

ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/babbage_test.go, ledger/conway.go, ledger/mary.go, ledger/shelley.go
Changes inside `Transactions() []Transaction` methods:
- in advance allocate memory for returning slice of Transactions (size of slice is known)
- use map to mark invalid transactions replacing the previous loop through an invalid slice.
Additionally, a `cachedTransactions` slice can be introduced within each struct, allowing for immediate return from the method when the slice is not nil, if you ok with that?
=> perf: a little optimization for Transactions() methods

protocol/blockfetch/client.go, protocol/chainsync/client.go, protocol/keepalive/client.go, protocol/localstatequery/client.go, protocol/localtxmonitor/client.go, protocol/localtxsubmission/client.go, protocol/txsubmission/server.go
=> fix: move protocol cleanup routines to Start()

ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/babbage_test.go, ledger/byron.go, ledger/conway.go, ledger/mary.go, ledger/shelley.go, ledger/tx.go
To enhance usability, this commit introduces the `IsValid` method within the `Transaction` interface. This allows easy determination of a transaction's validity status without the need for casting.
=> feat: add IsValid method to Transaction interface

protocol/handshake/messages.go, protocol/handshake/server.go, protocol/handshake/server_test.go, protocol/versions.go
This change should fix https://github.com/blinklabs-io/gouroboros/issues/530
Problem was happening because iterating through map is not deterministic.
Also there was uint64/uint16 differences
To test this fix, the only method available is to start the `func TestServerHandshakeRefuseVersionMismatch(t *testing.T)` test multiple times until line 211 in `internal/test/ouroboros_mock/connection.go` (`if !reflect.DeepEqual(msg, entry.InputMessage)`) is reached. Following these modifications, both messages should consistently match
=> fix: Random panic in handshake tests #530

protocol/handshake/server_test.go, protocol/protocol.go, utils/utils.go
Fix for https://github.com/blinklabs-io/gouroboros/issues/535
The Thread-Safe `DoneSignal` is introduced with the following features:
- The `Close` method can be called multiple times, but it will only trigger once.
- The `GetCh()` method returns a listen-only channel and should be called by all routines that listen for the closing event.
If either the `recvLoop` or `sendLoop` routines exits, it will trigger the closing of the `DoneSignal`. Subsequently, this will lead to the shutdown of the other routine and the `stateLoop`. The `stateLoop` will be finally finished after both the `recvLoop` and `sendLoop` have shut down (`p.waitGroup.Wait()`)
This pr does not fix https://github.com/blinklabs-io/gouroboros/issues/530 only makes all the protocol routines gracefully shutdown
=> fix: Goroutine leak in handshake server on version mismatch refusal #535

cbor/cbor.go, cbor/decode.go, cbor/encode.go, cbor/tags.go, cbor/tags_test.go, cbor/value.go, cbor/value_test.go, protocol/localtxmonitor/messages.go
This moves the handling for some custom CBOR tag types from cbor.Value to the generic encoder/decoder to make them more widely usable.
Fixes #548
=> feat: generic custom CBOR tag handling

cmd/gouroboros/query.go, ledger/babbage.go, protocol/localstatequery/client.go, protocol/localstatequery/queries.go
This adds support for parsing Babbage protocol parameter updates in transactions. It also updates the Babbage protocol params data structure used for local-state-query and makes it era-aware
Fixes #328
=> feat: babbage protocol parameters

connection.go
=> feat: expose handshake protocol version

protocol/handshake/client_test.go
=> test: additional handshake client tests

cbor/cbor.go, protocol/localstatequery/client_test.go
This tests a simple query, a simple query that requires the current era, a simple query that uses the Shelley query type, and a more complex query.
Fixes #321
=> test: local-state-query client tests

protocol/chainsync/client_test.go
=> test: chainsync client tests

ledger/byron.go, ledger/common.go, ledger/common_test.go
This adds support for decoding Byron transaction inputs and outputs, as well as enhances the Address type for Byron addresses
Fixes #285
=> feat: ledger support for Byron TX inputs/outputs

protocol/localtxmonitor/client_test.go
This adds tests for checking a node's mempool for a particular TX, retrieving the node's mempool size/capacity/count, and listing TXs from the mempool
Fixes #322
=> test: localtxmonitor client tests

ledger/byron.go
This rounds out the API interfaces for Byron blocks and transactions and implements Byron transaction hash generation
Fixes #206
=> feat: additional Byron ledger support

connection_manager.go, connection_manager_test.go, go.mod, go.sum
This updates the connection manager to use the new Connection ID instead of a user-provided int value.
Fixes #577
BREAKING CHANGE: the API interface for ConnectionManager is changing to use ConnectionId instead of an arbitrary user-provided value
=> feat!: use connection ID in connection manager

ledger/allegra.go, protocol/localstatequery/client.go
Test
```
era = Allegra, slot = 23068725, block_no = 5406744, id = e1a6bd60b491446a17f9696a5414e087e763cc6c0c6ccf3359ce5b755dca8abe
era = Allegra, slot = 23068772, block_no = 5406745, id = bac3854978e827644a6e711aae574f4e0353bfcec9c6960eaa08c923ae1704c8
era = Allegra, slot = 23068793, block_no = 5406746, id = 69c44ac1dda2ec74646e4223bc804d9126f719b1c245dadc2ad65e8de1b276d7
era = Mary, slot = 23068800, block_no = 5406747, id = a650a3f398ba4a9427ec8c293e9f7156d81fd2f7ca849014d8d2c1156c359b3a
era = Mary, slot = 23068966, block_no = 5406748, id = 6ba25afbbaf2c6c6d65f64987fb15ea7a86ce0e6414357d7b95e6df7d573539b
```
Closes #325
=> feat:add Allegra protocol parameters support

ledger/mary.go, ledger/shelley.go, ledger/shelley_test.go, protocol/localstatequery/client.go
```
era = Mary, slot = 39916796, block_no = 6236059, id = e72579ff89dc9ed325b723a33624b596c08141c7bd573ecfff56a1f7229e4d09
era = Alonzo, slot = 39916975, block_no = 6236060, id = 8959c0323b94cc670afe44222ab8b4e72cfcad3b5ab665f334bbe642dc6e9ef4
```
Closes #326
=> feat:add Mary protocol parameters support

ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/conway.go, ledger/mary.go, ledger/shelley.go, ledger/tx.go
=> feat: add support for TX attribute: protocol parameters update

ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/conway.go, ledger/mary.go, ledger/shelley.go, ledger/tx.go
This adds support for returning the collateral inputs (if any) from a transaction body.
Fixes #338
=> feat: TX collateral inputs support

ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/conway.go, ledger/mary.go, ledger/shelley.go, ledger/tx.go
=> feat: TX consumed/produced helper functions

ledger/verify_block.go
Copy the block verification functions from
https://github.com/cardano-foundation/cardano-ibc-incubator with minimal modifications.
=> feat: block verification functions

ledger/verify_block_body.go
Copy the get list of pool ID from (de)registration certificates functions from https://github.com/cardano-foundation/cardano-ibc-incubator with minimal modifications.
=> feat: pool id extraction functions

ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/conway.go, ledger/mary.go, ledger/shelley.go, ledger/tx.go
This adds support for decoding and retrieving governance proposal procedures from a TX
Fixes #344
=> feat: TX proposal procedures attribute

README.md, ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/conway.go, ledger/mary.go, ledger/shelley.go, ledger/tx.go
This adds a method for retrieving the current treasury value attribute from a TX
Fixes #626
=> feat: TX current treasury value attribute

ledger/alonzo.go, ledger/babbage.go
This adds custom marshaling functions to various TX output types to match the existing custom unmarshal functions
Fixes #654
=> feat: custom CBOR marshaling for TX outputs

protocol/localstatequery/localstatequery.go, protocol/localstatequery/server.go
This updates the callback function definitions for the server side of LocalStateQuery to use more specific types where possible
Fixes #353
=> feat: update local-state-query callback definitions

cbor/encode.go, cbor/encode_test.go, protocol/txsubmission/messages.go
This also slightly changes the way that indefinite-length lists work, as well as adds tests for indefinite-length lists
Fixes #659
=> feat: CBOR encode support for indefinite-length bytestrings

cbor/encode.go, go.mod, go.sum
The encoder mode we used previously now has unwanted side effects, so we create our own with only the options we need
=> chore(deps): update fxamacker/cbor to v2.7.0

ledger/alonzo.go, ledger/conway.go
=> feat: support for Conway redeemers and PlutusV3 TX witnesses

ledger/conway.go, protocol/localstatequery/client.go
=> feat: support for Conway protocol parameter updates

ledger/conway.go
=> fix: allocate map before assignment when decoding Conway redeemers

ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/common/address.go, ledger/common/address_test.go, ledger/common/common.go, ledger/common/common_test.go, ledger/compat.go, ledger/conway.go, ledger/mary.go, ledger/mary_test.go, ledger/shelley.go, ledger/tx.go, ledger/verify_block_body.go, networks.go
This is in preparation for further refactoring. Additionally, it:
* adds compatability types/functions to keep existing code working
* adds NewMultiAsset function to create MultiAsset from existing data
* switches to public interface for iterating over MultiAsset in various places
=> chore: move address and common types to sub-package

ledger/allegra.go, ledger/alonzo.go, ledger/babbage.go, ledger/byron.go, ledger/common/era.go, ledger/common/era_test.go, ledger/conway.go, ledger/era.go, ledger/mary.go, ledger/shelley.go
This also moves to a registration model for eras to avoid import cycles
=> chore: move era registry to sub-package

ledger/conway/conway.go
The protocol major/minor were historically separate fields due to a bug in the upstream implementation, but it has been fixed for the Conway era
=> fix: merge protocol minor/major Conway protocol params

ledger/allegra/allegra.go, ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/block.go, ledger/byron/byron.go, ledger/common/tx.go, ledger/conway/conway.go, ledger/mary/mary.go, ledger/shelley/shelley.go
=> feat: function to get block/tx numeric type

muxer/muxer.go, protocol/protocol.go
=> fix: protect against race condition on shutdown in muxer

cbor/cbor.go, ledger/allegra/allegra.go, ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/byron/byron.go, ledger/common/pparams.go, ledger/common/tx.go, ledger/conway/conway.go, ledger/mary/mary.go, ledger/shelley/shelley.go
This commit also:
* creates an interface type for protocol parameter updates
* stores CBOR for protocol parameter updates
* changes DecodeStoreCbor Cbor() to value receiver for more flexibility
=> feat: return epoch with protocol param updates

ledger/mary/mary.go, ledger/mary/pparams.go, ledger/mary/pparams_test.go
* update protocol parameter set from protocol param update spec
Fixes #743
=> feat: Mary protocol parameter updates

ledger/alonzo/alonzo.go, ledger/alonzo/genesis.go, ledger/alonzo/genesis_test.go, ledger/alonzo/pparams.go, ledger/alonzo/pparams_test.go, ledger/common/pparams.go
* update protocol parameter set from protocol param update spec
* update protocol parameter set from genesis
* move ExUnit types to common
* update types for genesis
Fixes #744
=> feat: Alonzo protocol parameter updates

cmd/common/cmdline.go, cmd/gouroboros/main.go, networks.go
Fixes #761
BREAKING CHANGE: the prototype for functions for getting a network changed to add a boolean return parameter to signify whether the network is known. The public root address/port fields have also been replaced with a list of bootstrap peers
=> feat: multiple bootstrap peers per network

protocol/localstatequery/client.go
If `localtxmonitor` => `Acquire` is called with a `nil` point (indicating the latest point), a bug occurs because the logger attempts to print the point's `Hash` and `slot`, even though point is `nil`
=> fix: Acquire nil point

cmd/gouroboros/chainsync.go, ledger/allegra/pparams_test.go, ledger/alonzo/pparams.go, ledger/alonzo/pparams_test.go, ledger/conway/pparams.go, ledger/mary/pparams_test.go, ledger/shelley/pparams.go, ledger/shelley/pparams_test.go, ledger/verify_block.go, protocol/handshake/server.go, protocol/localstatequery/client.go
=> fix: guard possible nil panics

protocol/txsubmission/server.go
We avoid the potential for panic due to send on closed channel by not closing the channels. We instead use a select block with DoneChan to detect shutdown
=> fix: avoid panic in txsubmission

protocol/blockfetch/client.go
issue #774 
Unlock busyMutex when returning `ProtocolShuttingDownError`
=> fix: connection.BlockFetch().Client.GetBlock potential deadlock

protocol/localstatequery/client.go, protocol/localstatequery/client_test.go, protocol/localstatequery/localstatequery.go, protocol/localstatequery/messages.go, protocol/localstatequery/messages_test.go, protocol/localstatequery/server.go
* rename (Re)AcquireNoPoint to (Re)AcquireVolatileTip
* add new messages for ImmutableTip
* add client functions for acquiring volatile/immutable tip
* change Acquire callback signature for immutable trip
Fixes #766
=> feat: support for acquire immutable tip in local-state-query

protocol/localstatequery/client.go, protocol/localstatequery/error.go, protocol/localstatequery/localstatequery.go, protocol/localstatequery/server.go
* switch custom errors to vars instead of types
* merge Acquire/ReAcquire callbacks
* remove Done callback
* add ability to return result in Query callback
* automatically send acquire result response
* automatically send query result
=> refactor: improve local-state-query callback interface

protocol/localstatequery/queries.go
We need a concrete type rather than an interface for decoding
=> fix: adjust UTxO by Txin query field type

protocol/localstatequery/queries.go
=> fix: additional field in EraHistory query

protocol/chainsync/chainsync.go, protocol/chainsync/client.go
This provides a "raw" variant of the RollForward callback that bypasses any decoding and returns only the raw bytes for the header or block
=> feat: optionally provide raw header/block bytes in chainsync callback

ledger/common/address.go
=> fix: CBOR marshaling for Byron addresses

ledger/common/address.go, ledger/common/address_test.go
This adds proper support for Byron addresses, including building one from parts.
Fixes #540
=> feat: Byron address support

cbor/decode.go, ledger/conway/conway.go, ledger/shelley/shelley.go, ledger/tx_test.go
Conway-era TX inputs using CBOR tag 258 (sets) could be implicitly decoded by earlier eras, but this doesn't match the behavior of cardano-node. We explicitly prevent this from happening to allow proper identification of TX types
=> fix: prevent Conway TX inputs from being decoded as Shelley TX input

protocol/chainsync/client.go
We now send pipelined RequestNext messages in batches instead of an initial batch and subsequent single messages. This potentially improves performance and reduces pressure on mini-protocol buffers
=> refactor: send RequestNext in batches for chainsync pipelining

ledger/common/address.go, ledger/common/state.go, ledger/common/tx.go, ledger/shelley/errors.go, ledger/shelley/rules.go, ledger/shelley/rules_test.go, ledger/shelley/shelley.go
This implements the remainder of the Shelley era "Utxo" validation rules, as well as tests for each. It also includes the following changes to support the validation rules:
* expose address network ID, type, and Byron attributes
* add helpers for ShelleyTransactionInputSet to make use in tests easier
* change UtxoState interface to lookup a single UTxO at a time
* add NetworkId() to LedgerState interface
* add String() to TransactionInput interface
Fixes #875
=> feat: Shelley era 'Utxo' validation rules

ledger/mary/errors.go, ledger/mary/rules.go, ledger/mary/rules_test.go
=> feat: Mary era 'Utxo' validation rules

networks.go
This introduces a `devnet` network with the magic number of 42, which is used in local testing.
=> feat: devnet network

cbor/value.go, cbor/value_test.go
* use a pointer for map keys for non-comparable types in cbor.Value
* allow arbitrary tag types for cbor.Value
Signed-off-by: Aurora Gaffney <aurora@blinklabs.io>
=> fix: better handling for arbitrary CBOR data structures

ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/babbage/babbage_test.go, ledger/common/native_script.go, ledger/common/witness.go, ledger/conway/conway.go, ledger/mary.go, ledger/mary/mary.go, ledger/shelley/shelley.go
=> feat: define TX witness types

ledger/allegra/allegra.go, ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/byron/byron.go, ledger/common/tx.go, ledger/common/witness.go, ledger/conway/conway.go, ledger/mary/mary.go, ledger/shelley/shelley.go
=> feat: common interface for accessing TX witnesses

ledger/allegra/rules.go, ledger/allegra/rules_test.go, ledger/alonzo/alonzo.go, ledger/alonzo/pparams.go, ledger/babbage/pparams.go, ledger/conway/conway.go, ledger/conway/pparams.go, ledger/mary/rules.go, ledger/mary/rules_test.go, ledger/shelley/pparams.go, ledger/shelley/rules.go, ledger/shelley/rules_test.go, ledger/shelley/shelley.go, ledger/tx_test.go
Formatting only, no additional changes
=> chore: make format golines

ledger/alonzo/alonzo.go, ledger/alonzo/pparams.go, ledger/alonzo/pparams_test.go, ledger/babbage/pparams.go, ledger/babbage/pparams_test.go, ledger/common/common.go, ledger/common/pparams.go, ledger/common/tx.go, ledger/conway/conway.go, ledger/conway/pparams.go, ledger/conway/pparams_test.go
Signed-off-by: Aurora Gaffney <aurora@blinklabs.io>
=> refactor: merge duplicate ExUnits types

cbor/value.go
Potential fix for [https://github.com/blinklabs-io/gouroboros/security/code-scanning/13](https://github.com/blinklabs-io/gouroboros/security/code-scanning/13)
To fix the problem, we should avoid manually constructing JSON strings and instead use a structured API that handles quoting and escaping automatically. This can be achieved by using the `json.Marshal` function to serialize the key-value pairs into JSON format.
- Replace the manual string construction with `json.Marshal` to ensure proper escaping of quotes and other special characters.
- Update the `generateAstJsonMap` function to use `json.Marshal` for constructing the JSON string.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 13: Potentially unsafe quoting

ledger/alonzo/errors.go, ledger/alonzo/rules.go, ledger/alonzo/rules_test.go
=> feat: Alonzo era 'Utxo' validation rules

ledger/alonzo/genesis.go, ledger/byron/genesis.go, ledger/conway/genesis.go, ledger/shelley/genesis.go
Disable until #926 is resolved which will remove these comments
=> chore: disable musttag linter on genesis structs

ledger/allegra/rules.go, ledger/alonzo/rules.go, ledger/babbage/errors.go, ledger/babbage/rules.go, ledger/babbage/rules_test.go, ledger/mary/rules.go
=> feat: Babbage era 'Utxo' validation rules

ledger/conway/conway.go, ledger/conway/errors.go, ledger/conway/rules.go, ledger/conway/rules_test.go
This also moves the Babbage-era disjoint ref inputs validation to Conway. It was defined in Babbage in the Haskell code, but it only actually does anything in the Conway era
Fixes #880
=> feat: Conway era 'Utxo' validation rules

.golangci.yml
This disables the `asasalint` and `recvcheck` checks due to failing. There are open issues to resolve them, individually.
=> ci(golangci-lint): use bugs and performance presets

ledger/allegra/rules_test.go, ledger/alonzo/rules_test.go, ledger/babbage/rules.go, ledger/babbage/rules_test.go, ledger/conway/rules.go, ledger/conway/rules_test.go, ledger/mary/rules_test.go, ledger/shelley/rules.go, ledger/shelley/rules_test.go
Also, because you cannot re-register a registered stake key or de-register and unregistered stake key, we can always apply the key deposit/refund for one of those certs and do not need to query
=> feat: account for stake deregistration in validation rules

protocol/protocol.go
=> refactor: prefetch messages from muxer in protocol

ledger/allegra/rules_test.go, ledger/alonzo/rules_test.go, ledger/babbage/rules_test.go, ledger/common/certs.go, ledger/common/credentials.go, ledger/common/gov.go, ledger/conway/rules_test.go, ledger/mary/rules_test.go, ledger/shelley/rules_test.go
=> chore: rename StakeCredential to Credential

ledger/alonzo/genesis.go, ledger/alonzo/genesis_test.go, ledger/byron/genesis.go, ledger/byron/genesis_test.go, ledger/conway/genesis.go, ledger/conway/genesis_test.go, ledger/shelley/genesis.go
1. Added missing `json` struct tags to multiple genesis structs.
2. Remove nolint comments from reader constructors
3. Add unit tests to verify JSON decoding
Closes #926
=> Add JSON labels to Genesis structs

internal/test/ledger/ledger.go, ledger/common/credentials.go
This makes it more like other hashes where we have defined which hash type it should be underneath.
=> fix(ledger): use a named type for credential hash

ledger/babbage/rules.go, ledger/conway/rules.go, ledger/shelley/rules.go
We fall back to encoding to CBOR ourselves if there is no stored CBOR
=> fix: use stored CBOR in TX validation rules

ledger/common/address.go, ledger/common/credentials.go
This makes the types interchangeable with Blake2b224 for convenience. It also allows using the Bytes() function when using the more specific types
=> refactor: make CredentialHash/AddrKeyHash aliases of Blake2b224

ledger/allegra/allegra.go, ledger/alonzo/alonzo.go, ledger/alonzo/rules.go, ledger/alonzo/rules_test.go, ledger/babbage/babbage.go, ledger/babbage/rules.go, ledger/babbage/rules_test.go, ledger/conway/conway.go, ledger/conway/rules.go, ledger/conway/rules_test.go, ledger/mary/mary.go, ledger/shelley/shelley.go
* subtract 1 byte from TX size in Alonzo+ when calculating fee
* add error handling around CBOR encode that should "never fail"
* rename 'IsTxValid' to 'TxIsValid' for consistency
* change nil check to length check
=> fix: use correct TX size calc for min-fee in Alonzo and later

ledger/byron/genesis.go, ledger/common/genesis.go, ledger/conway/genesis.go, ledger/shelley/genesis.go, ledger/shelley/genesis_test.go
1. Added json tags to all the genesis structs.
Closes #926
=> fix(genesis): Added json labels to all genesis structs

ledger/common/certs.go, ledger/common/common_test.go
1. Added a new Type() uint method to the Certificate interface.
2. Added this method for all 19 certificate types using the existing CertType field. 
3. Added a test function to validate the method Type() returns the expected values.
Closes #636
=> feat(ledger): Add a method to get the Certificate type to the interface

cmd/gouroboros/chainsync.go, ledger/allegra/allegra.go, ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/babbage/babbage_test.go, ledger/byron/byron.go, ledger/common/block.go, ledger/common/tx.go, ledger/conway/conway.go, ledger/mary/mary.go, ledger/shelley/shelley.go, ledger/verify_block_body.go, protocol/blockfetch/client_test.go, protocol/chainsync/client.go, protocol/chainsync/client_test.go, protocol/localtxmonitor/server.go
This switches from returning the string representation of a block/TX hash to the underlying Blake2b256 type containing the hash bytes. Those bytes are used all over the place, and it's cumbersome to need to use hex.DecodeString() everywhere to convert back to bytes
BREAKING CHANGE: library consumers will need to convert from bytes to string before use
=> refactor: return Blake2b256 for block and TX hash

ledger/allegra/allegra.go, ledger/allegra/rules_test.go, ledger/alonzo/alonzo.go, ledger/alonzo/rules_test.go, ledger/babbage/babbage.go, ledger/babbage/rules_test.go, ledger/common/tx.go, ledger/conway/conway.go, ledger/conway/rules_test.go, ledger/mary/mary.go, ledger/mary/rules_test.go, ledger/shelley/shelley.go
=> refactor: remove embeds in per-era TransactionBody types

ledger/allegra/allegra.go, ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/byron/byron.go, ledger/common/certs.go, ledger/common/credentials.go, ledger/conway/conway.go, ledger/mary/mary.go, ledger/shelley/shelley.go
This removes multiple uses of reflection during decoding by creating a static type of the same shape in UnmarshalCBOR. This works because the UnmarshalCBOR function from the original type does not follow to the new type, so generic decoding behavior is used instead.
This was only possible after removing embedding in any of the types that we want to capture the original CBOR on. The promoted UnmarshalCBOR function from the embedded type(s) were being called otherwise, which did not produce the desired result.
=> refactor: remove reflection when storing CBOR on decode

cbor/cbor.go, ledger/allegra/pparams.go, ledger/allegra/pparams_test.go, ledger/allegra/rules.go, ledger/allegra/rules_test.go, ledger/alonzo/pparams.go, ledger/alonzo/pparams_test.go, ledger/alonzo/rules.go, ledger/alonzo/rules_test.go, ledger/babbage/pparams.go, ledger/conway/pparams.go, ledger/mary/pparams.go, ledger/mary/pparams_test.go, ledger/mary/rules.go, ledger/mary/rules_test.go, ledger/shelley/pparams.go, protocol/localstatequery/queries.go
* make Allegra/Mary pparams type aliases of Shelley types
* remove embedded types from Alonzo pparams
* remove use of reflection for decoding pparams CBOR
* remove now unused UnmarshalCbor function from DecodeStoreCbor
Fixes #982
=> refactor: remove embedding in pparam types

ledger/byron.go, ledger/byron/byron.go, ledger/tx.go, ledger/tx_test.go
1. Enabled support for decoding Byron transaction outputs in NewTransactionOutputFromCbor
2. Uncommented Byron handling in DetermineTransactionType to detect Byron transactions
3.  Added test cases for DetermineTransactionType with valid Byron CBOR.
Closes #849
=> feat(ledger): Add Byron transaction output support to NewTransactionOutputFromCbor 

ledger/alonzo/genesis_test.go, ledger/byron/genesis_test.go, ledger/common/common_test.go, ledger/conway/genesis_test.go
We only want tests to log when there's a failure to keep the output clean
=> chore: remove positive logging in tests

protocol/chainsync/messages.go, protocol/chainsync/messages_test.go, protocol/chainsync/server.go, protocol/chainsync/wrappers.go
1. Updated NewWrappedHeader to return an error when CBOR decoding fails.
2. Modified NewMsgRollForwardNtN to return the wrapped header error.
3. Added unit test for NewMsgRollForwardNtN to verify error propagation from NewWrappedHeader with corrupted CBOR.
4. Modified existing test case of NewMsgRollForwardNtN function.
Closes #856
=> fix(chainsync): Handle error in chainsync.NewWrappedHeader

.github/workflows/go-test.yml, .gitmodules, cmd/gouroboros/query.go, protocol/localstatequery/client_test.go, protocol/localstatequery/messages_test.go, protocol/localstatequery/queries.go
Adds cardano-blueprint submodule that contains first examples of local state query query and result data.
The included getSystemStart result example was generated using the actual data type used by the haskell server implementation. To make the example roundtrip, big integers (> int64) must be supported.
Closes #992
=> test(protocol): localstatequery using cardano blueprint tests

connection.go, muxer/muxer.go
This removes a race condition that caused random failures when the remote peer sent a handshake message before we have registered the protocol
=> fix: require explicit muxer start before handshake

ledger/common/certs.go
1. Implemented Utxorpc() function for all of the Conway governance certificates. 
Closes #850
=>  feat(certs): Implemented Utxorpc() for Conway governance certs

ledger/alonzo/genesis.go, ledger/alonzo/genesis_test.go, ledger/alonzo/pparams.go, ledger/alonzo/pparams_test.go, ledger/babbage/pparams.go
1. Changes added to support cost models when updating Alonzo protocol params from genesis config - mapped string keys to numeric indexes
2. Changes to support both array and map from genesis files
3. Added unit tests for the changes
Closes #852 
Closes #963
=> feat: changes to support cost models while updating Alonzo protocols through genesis config

ledger/babbage/rules.go, ledger/babbage/rules_test.go
1. Fixed an uint underflow in UtxoValidateCollateralEqBalance by skipping validation when no valid collateral UTxOs are found.  
2. Added a unit test to ensure collateral return subtraction is skipped when collBalance is zero, avoiding invalid balance validation.
Closes #1000
=> feat(ledger/babbage): Integer underflow issue in babbage.UtxoValidateCollateralEqBalance

ledger/shelley/pparams_test.go
Added all the below unit tests for shelly transaction UtxoRpc  conversions.
1. Added TestShelleyTransactionInput_Utxorpc to verify TxInput conversion.
2. Added TestShelleyTransactionOutput_Utxorpc to validate TxOutput mapping.
3. Added TestShelleyTransactionBody_Utxorpc to test full transaction body mapping (fee, inputs, outputs).
4. Added TestShelleyTransaction_Utxorpc to ensure ShelleyTransaction delegates correctly to Body.Utxorpc().
=> test(ledger): UTxO RPC functions for Shelley Transactions

connection.go, muxer/muxer.go
1. Replaced plain io.EOF with descriptive wrapped errors like peer closed the connection while reading header: EOF
in Muxer.readLoop(). 
2. Updated downstream handling in setupConnection() function and muxer error forwarding to preserve
the wrapped errors.
Closes #518
=> fix(muxer): Return better error message when the peer closes the connection

ledger/shelley/genesis.go, ledger/shelley/genesis_test.go
The `devnet` config.json we ship in the container uses a slot length of 0.1
=> fix: slot length is a ratio

ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/byron/byron.go, ledger/common/tx.go, ledger/mary/mary.go, ledger/shelley/shelley.go
1. Extended common.TransactionOutput interface with GetScriptRef() method
2. Implemented GetScriptRef() in BabbageTransactionOutput to return actual ScriptRef (CBOR.LazyValue)
3. Added stub GetScriptRef() implementations returning nil in other eras such as Shelley, Mary, Alonzo, and Byron
Closes #1044
=> feat: Support getting ScriptRef from TransactionOutput interface

ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/byron/byron.go, ledger/common/script.go, ledger/common/script_test.go, ledger/common/tx.go, ledger/mary/mary.go, ledger/shelley/shelley.go
=> feat: support for decoding script ref

ledger/allegra/allegra.go, ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/conway/conway.go, ledger/mary/mary.go, ledger/shelley/shelley.go
We also switch to using a pointer to give us a more usable zero value for CBOR encoding
Fixes #1058
=> refactor: use separate type for TX pparam update

ledger/alonzo/alonzo.go, ledger/alonzo/pparams_test.go
This also renames the TX output datum hash struct field for consistency
Fixes #1059
=> fix: exclude empty datum hash from Alonzo TX output CBOR

ledger/byron/genesis.go, ledger/common/address.go
This makes Byron address bytes wrapped in a bytestring for CBOR, the same as Shelley addresses. It also switches the Byron genesis UTxO code to explicitly use address bytes rather than use the CBOR representation
Fixes #1066
=> fix: Byron address CBOR encoding

cbor/tags.go, ledger/alonzo/alonzo.go, ledger/alonzo/rules_test.go, ledger/babbage/babbage.go, ledger/babbage/rules_test.go, ledger/conway/conway.go, ledger/conway/pparams_test.go, ledger/conway/rules_test.go
This creates a generic CBOR set type wrapper that supports the optional encoding format for various transaction body attributes
Fixes #1063
Fixes #1064
Fixes #1065
=> refactor: use CBOR set tags when encoding TX body fields

protocol/txsubmission/client.go, protocol/txsubmission/error.go
=> feat: support for client Done in TxSubmission

protocol/txsubmission/server.go
=> refactor: allow cleanly stopping TxSubmission server

ledger/common/gov.go, ledger/common/gov_test.go
1. Implemented Voter.ToPlutusData(), Vote.ToPlutusData(), and VotingProcedure.ToPlutusData() methods.
2. Converts voter types (Constitutional Committee/DRep/Staking Pool) to PlutusData by wrapping hashes in StakeCredential structures with different constructor numbers (0/1/2).
3. Created gov_test.go with test coverage for all three types, testing all voter types, vote types.
Closes #1105
=> feat(ledger): Add ToPlutusData() function to gov vote-related types

ledger/common/gov.go, ledger/common/gov_test.go
1. Implemented ToPlutusData() for GovAnchor, GovActionId, ProposalProcedure, GovActionWrapper, ParameterChangeGovAction, HardForkInitiationGovAction, TreasuryWithdrawalGovAction, NoConfidenceGovAction, UpdateCommitteeGovAction, NewConstitutionGovAction, InfoGovAction
2. Added unit tests for all the ToPlutusData() implemented above.
Closes #1106
=> feat(ledger): Added ToPlutusData() function to gov proposal related types

ledger/alonzo/alonzo.go, ledger/alonzo/alonzo_test.go, ledger/common/redeemer.go, ledger/common/tx.go, ledger/conway/conway.go, ledger/conway/conway_test.go, ledger/conway/rules_test.go
This also moves the Conway redeemer key/value types to common so they can be reused for iteration
Fixes #1126
=> refactor: allow easier iteration of redeemers

cbor/debug.go
The only function is CBOR-related, so moving it and getting rid of the `utils` package.
=> refactor(cbor): move debug from utils to cbor package

ledger/common/script.go, ledger/common/script_test.go
=> refactor: helper for generating script hash

ledger/common/script.go, ledger/common/script_test.go
This also adds a test for generating the native script hash
Fixes #1139
=> fix: retain data on CBOR unmarshal of native script

go.mod, go.sum, ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/byron/byron.go, ledger/common/data.go, ledger/common/data_test.go, ledger/common/tx.go, ledger/conway/conway.go, ledger/mary/mary.go, ledger/shelley/shelley.go
=> refactor: decode Plutus datum as data.PlutusData

ledger/common/script.go, ledger/common/script_test.go
=> fix: script ref CBOR marshaling

ledger/alonzo/alonzo.go, ledger/babbage/babbage.go, ledger/common/tx.go, ledger/conway/conway.go, ledger/shelley/shelley.go
1. Used common.PlutusV1Script, PlutusV2Script, and PlutusV3Script types instead of raw []byte when returning scripts from transaction witness sets.
Closes #1146
=> refactor: Use common.Script types when returning Plutus scripts from witness set

go.mod, go.sum, ledger/babbage/babbage.go
This also updates blinklabs-io/plutigo to v0.0.10
=> fix: retain original datum CBOR on decode

ledger/byron/genesis.go, ledger/byron/genesis_test.go
1. Added custom type `ByronGenesisFtsSeed` with UnmarshalJSON/MarshalJSON.
2. Allow ftsSeed to be parsed from either a JSON string or an empty object.
3. Update tests to expect ByronFtsSeed instead of plain string and added optional test coverage for empty object case.
Closes #1039
=> fix(ledger/byron): ByronGenesis.FtsSeed can be object

ledger/common/certs.go
=> chore(ledger): move drep function near others

connection.go, protocol/leiosnotify/client.go, protocol/leiosnotify/leiosnotify.go, protocol/leiosnotify/messages.go, protocol/leiosnotify/server.go
This is an initial implementation of the LeiosNotify protocol as described in CIP-0164. Many of the details are fudged since the protocol is not fully specified in the CIP.
=> feat: initial LeoisNotify protocol

protocol/chainsync/client_test.go, protocol/chainsync/messages.go, protocol/chainsync/messages_test.go, protocol/chainsync/server.go
=> Added error handling for NewMsgRollForwardNtC

ledger/conway/conway_test.go
1. Added TestConwayTx_CborRoundTrip_UsingCborEncode to ensure CBOR round-trip for a Conway transaction.
Closes #207
=> feat(conway): Added CBOR round trip test for conway transaction

cmd/tx-submission/main.go, ledger/common/script/context.go, ledger/conway/conway_test.go
Introduction of Leios primitives and the Endorser Block's TxReference means we have a different Hash and Id for Transactions from Leios going forward.
=> fix: use Id instead of Hash for transactions
